import molpher
import warnings

from molpher.swig_wrappers.core import TraverseCallback, TraverseOper, MolpherMol, ExplorationTreeSnapshot


class Callback(TraverseCallback):
    """
    :param callback: callable with one positional argument
    :type callback: any callable object

    Basic callback class used to traverse the tree in `ExplorationTree.traverse()` method.

    It registers a callable and calls it every time a `morph` is processed.

    """

    def __init__(self, callback):
        super(self.__class__, self).__init__()
        self._callback = callback

    def processMorph(self, morph):
        """
        Calls the registered callback for a `morph`

        :param morph: morph in a tree
        :type morph: `MolpherMol`
        """

        self._callback(morph)

class ExplorationTree(molpher.swig_wrappers.core.ExplorationTree):
    """
    :param params: the morphing parameters (optional if ``source`` is specified)
    :type params: `molpher.swig_wrappers.core.ExplorationParameters` or any of its derived classes
    :param source: SMILES of the source molecule
    :type source: `str`
    :param target: SMILES of the target molecule (optional)
    :type target: `str`

    ..  note:: When ``params`` are specified, ``source`` and ``target`` are ignored.

    ..  note:: If the target molecule is missing a single carbon atom is supplied instead as a placeholder.

    This specialized version of `molpher.swig_wrappers.core.ExplorationTree`
    implements some additional functionality for ease of use from Python.

    """

    def __init__(self, params=None, source=None, target=None):
        if params and (source or target):
            warnings.warn(
                "Both parameters and a source or a target specified. Using the values in parameters..."
                , RuntimeWarning
            )
        if params and (params.__class__ == molpher.core.ExplorationParameters
                or params.__class__ == molpher.wrappers.ExplorationParameters): # FIXME: check only for the base class molpher.wrappers.ExplorationParameters
            super(ExplorationTree, self).__init__(params)
        elif params:
            _params = molpher.core.ExplorationParameters(**params)
            super(ExplorationTree, self).__init__(_params)
        elif source:
            if not target:
                super(ExplorationTree, self).__init__(source)
            else:
                super(ExplorationTree, self).__init__(source, target)
        else:
            raise RuntimeError('You must specify either `params` or `source`.')

        self._callback_class = Callback

    @property
    def params(self):
        """
        A dictionary representing the current `exploration parameters`.

        It is possible to assign a new dictionary to update the current parameters.
        Only parameters defined in the supplied dictionary are changed.

        :return: current parameters
        :rtype: `dict`
        """
        params = molpher.core.ExplorationParameters(parameters=self.getParams())
        return params.param_dict

    @params.setter
    def params(self, params):
        if params.__class__ == molpher.core.ExplorationParameters \
                or params.__class__ == molpher.wrappers.ExplorationParameters: # FIXME: check only for the base class molpher.wrappers.ExplorationParameters
            self.setParams(params)
        else:
            new = molpher.core.ExplorationParameters(parameters=self.getParams())
            new.param_dict = params
            self.setParams(new)

    @property
    def generation_count(self):
        """
        Number of `morph generations <morph generation>` connected to the tree so far.

        :return:
        :rtype: `int`
        """

        return self.getGenerationCount()

    @property
    def path_found(self):
        """
        Shows if the `target molecule` is present in this tree.

        :return:
        :rtype: `bool`
        """

        return self.isPathFound()

    @property
    def leaves(self):
        """
        The current leaves of the tree.

        :return: the current leaves of the tree as instances of `MolpherMol`
        :rtype: `tuple`
        """

        return self.fetchLeaves()

    @property
    def candidates(self):
        """
        Moprhs generated by a single call to `generateMorphs()`.

        :return: the `candidate morphs` as instances of `MolpherMol`
        :rtype: `tuple`
        """

        return self.getCandidateMorphs()

    @property
    def candidates_mask(self):
        """
        A `tuple` of `bool` objects that serve as means of filtering the `candidate morphs`.
        Each `morph` in `candidates` has a `bool` variable assigned to it in this `tuple`
        -- only morphs with `True` at the appropriate position are added to the tree when `extend`
        is called.

        It can be changed by supplying a new one to the `setCandidateMorphsMask()` method.

        :return: currently selected `candidate morphs` represented as a `tuple` of `bool` objects
        :rtype: `tuple`
        """

        return self.getCandidateMorphsMask()

    @candidates_mask.setter
    def candidates_mask(self, mask):
        self.setCandidateMorphsMask(mask)

    @property
    def thread_count(self):
        """
        Maximum number of threads this instance will use for its computations.

        :return: number of threads
        :rtype: `int`
        """

        return self.getThreadCount()

    @thread_count.setter
    def thread_count(self, val):
        self.setThreadCount(val)

    def traverse(self, callback, start_mol = None):
        """
        This method can be used to traverse the whole tree structure (or just a subtree)
        starting from root to leaves.

        The method takes a callback function that accepts a single argument. It then
        traverses the whole tree starting from its root (or root of a specified subtree) and
        calls the supplied function with the currently encountered morphs as its argument.

        A subtree can be specified by supplying its root as the optional ``start_mol`` argument.

        :param callback:
        :type callback: a callable object that takes a single argument
        :param start_mol: the root of a subtree to explore as canonical SMILES or `MolpherMol` instance
        :type start_mol: `str` or `MolpherMol`
        :return:
        :rtype:
        """

        if start_mol and type(start_mol) == MolpherMol:
            TraverseOper(self, self._callback_class(callback), start_mol)()
        elif start_mol:
            mol = self.fetchMol(start_mol)
            TraverseOper(self, self._callback_class(callback), mol)()
        else:
            cb = self._callback_class(callback)
            TraverseOper(self, cb)()

    @staticmethod
    def createFromSnapshot(snapshot):
        """
        Creates a tree from a file.

        :param snapshot: a path to a snapshot or an instance of `ExplorationTreeSnapshot`
        :type snapshot: `str` ot `ExplorationTreeSnapshot`
        :return: new tree instance
        :rtype: `ExplorationTree`
        """

        if type(snapshot) == str:
            template = ExplorationTreeSnapshot.load(snapshot)
            tree = molpher.swig_wrappers.core.ExplorationTree.createFromSnapshot(template)
        else:
            tree = molpher.swig_wrappers.core.ExplorationTree.createFromSnapshot(snapshot)
        tree.__class__ = ExplorationTree
        return tree

    def saveSnapshot(self, name):
        """
        Saves current instance as a file.

        :param name: path to the saved file
        :type name: `str`
        """

        snapshot = self.createSnapshot()
        snapshot.save(name)