/*
 Copyright (c) 2012 Vladimir Fiklik
 Copyright (c) 2012 Petr Koupy

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "NetbeansHack.h"

#include <string>
#include <list>

#include <boost/cstdint.hpp>
#include <boost/serialization/vector.hpp>

#include <RCF/Idl.hpp>

#include "MolpherParam.h"
#include "MolpherMolecule.h"
#include "IterationSnapshot.h"
#include "JobGroup.h"
#include "NeighborhoodTask.h"

RCF_BEGIN(BackendIfc, "BackendIfc")
    C(RCF_METHOD_V1(void, InitClient, std::string &))
    C(RCF_METHOD_R2(boost::uint32_t, CreateJob, IterationSnapshot, std::string))
    C(RCF_METHOD_V2(void, WakeJob, boost::uint32_t, std::string))
    C(RCF_METHOD_V2(void, SleepJob, boost::uint32_t, std::string))
    C(RCF_METHOD_V2(void, RemoveJob, boost::uint32_t, std::string))
    C(RCF_METHOD_V3(void, ChangeJobOrder, boost::uint32_t, boost::int32_t, std::string))
    C(RCF_METHOD_R2(bool, ValidateJobPassword, boost::uint32_t, std::string))
    C(RCF_METHOD_R3(IterationSnapshot, GetJobHistory, boost::uint32_t, boost::uint32_t, bool &))
    C(RCF_METHOD_R3(bool, SetFingerprintSelector, boost::uint32_t, boost::int32_t, std::string))
    C(RCF_METHOD_R3(bool, SetSimCoeffSelector, boost::uint32_t, boost::int32_t, std::string))
    C(RCF_METHOD_R3(bool, SetDimRedSelector, boost::uint32_t, boost::int32_t, std::string))
    C(RCF_METHOD_R3(bool, SetChemOperSelectors, boost::uint32_t, std::vector<boost::int32_t>, std::string))
    C(RCF_METHOD_R3(bool, SetParams, boost::uint32_t, MolpherParam, std::string))
    C(RCF_METHOD_R3(bool, SetDecoys, boost::uint32_t, std::vector<MolpherMolecule>, std::string))
    C(RCF_METHOD_R3(bool, AddPruned, boost::uint32_t, std::vector<MolpherMolecule>, std::string))
    C(RCF_METHOD_V1(void, EnqueueNeighborhoodTask, NeighborhoodTask))
    C(RCF_METHOD_V1(void, SkipNeighborhoodTask, boost::posix_time::ptime))
RCF_END(BackendIfc)

RCF_BEGIN(FrontendIfc, "FrontendIfc")
    C(RCF_METHOD_V1(void, AcceptJobs, JobGroup))
    C(RCF_METHOD_V1(void, AcceptIteration, IterationSnapshot))
    C(RCF_METHOD_V1(void, AcceptNeighborhoodTaskResult, NeighborhoodTaskResult))
RCF_END(FrontendIfc)
